src/: use dmidecode logs alongside decode-dimms
dts-hclmgr: update the generated script

Signed-off-by: Kamil Aronowski <kamil.aronowski@3mdeb.com>

diff --git a/dts-hclmgr b/dts-hclmgr
--- a/dts-hclmgr
+++ b/dts-hclmgr
@@ -286,6 +286,12 @@ inspect_args() {
 # lib/dasharo.sh
 # shellcheck disable=SC2154
 
+log() {
+  if [ "$quiet" != "1" ]; then
+    echo "$@" >&2
+  fi
+}
+
 extract_dasharo_version() {
   local dmidecode_file="$1"
   local dasharo_line
@@ -339,9 +345,7 @@ perform_extraction() {
 
   # Unpack the tar.gz file into the directory
   if ! tar -xzf "$hcl_report" -C "$dir_name" >/dev/null 2>&1; then
-    if [ "$quiet" != "1" ]; then
-      echo "Error: Failed to extract archive: $hcl_report"
-    fi
+    log "Error: Failed to extract archive: $hcl_report"
     exit 1
   fi
 }
@@ -366,6 +370,26 @@ extract_lookup_string_from_decode_dimms() {
   echo "$cleaned"
 }
 
+extract_lookup_string_from_dmidecode() {
+  local handle_id="$1"
+  local file_contents="$2"
+  local lookup_string="$3"
+
+  # Find the line number of the given memory device line
+  device_line_number=$(echo "$file_contents" | awk '/'"$handle_id"'/ {print NR; exit}')
+
+  # Find the first occurrence of lookup string after the given bank line
+  match_line=$(echo "$file_contents" | awk -v line="$device_line_number" 'NR > line && /'"$lookup_string"'/ {print NR; exit}')
+
+  lookup_string_extracted=$(echo "$file_contents" | awk "NR == $match_line")
+
+  restul_tmp=$(echo "$lookup_string_extracted" | awk -F "$lookup_string" '{print $2}')
+
+  # Trim leading and trailing whitespace
+  cleaned=$(echo "$restul_tmp" | awk '{$1=$1;print}')
+  echo "$cleaned"
+}
+
 # Return the appropriate HCL file path
 get_hcl_file_path() {
   local board_name="$1"
@@ -373,10 +397,13 @@ get_hcl_file_path() {
   local base_path="docs/docs/resources/hcl/$category"
 
   case "$board_name" in
-  "PRO Z690-A WIFI DDR4"*) echo "$base_path/pro-z690-a-wifi-ddr4.md" ;;
-  "PRO Z690-A WIFI"*) echo "$base_path/pro-z690-a-wifi.md" ;;
-  "PRO Z790-P WIFI DDR4"*) echo "$base_path/pro-z790-p-wifi-ddr4.md" ;;
-  "PRO Z790-P WIFI"*) echo "$base_path/pro-z790-p-wifi-ddr4.md" ;;
+  "PRO Z690-A DDR4(MS-7D25)") echo "$base_path/pro-z690-a-wifi-ddr4.md" ;;
+  "PRO Z690-A (MS-7D25)") echo "$base_path/pro-z690-a-wifi.md" ;;
+  "PRO Z690-A WIFI DDR4(MS-7D25)") echo "$base_path/pro-z690-a-wifi-ddr4.md" ;;
+  "PRO Z690-A WIFI (MS-7D25)") echo "$base_path/pro-z690-a-wifi.md" ;;
+  "PRO Z790-P (MS-7E06)") echo "$base_path/pro-z790-p-wifi.md" ;;
+  "PRO Z790-P WIFI DDR4 (MS-7E06)") echo "$base_path/pro-z790-p-wifi-ddr4.md" ;;
+  "PRO Z790-P WIFI (MS-7E06)") echo "$base_path/pro-z790-p-wifi.md" ;;
   *)
     echo "Error: Unknown or unsupported board: $board_name" >&2
     return 1
@@ -433,6 +460,44 @@ update_table() {
   fi
 
   rm -f before.md table.md table_sorted.md
+}
+
+# Use in a loop in memory_command.sh
+generate_memory_table_entry() {
+  local num_modules="$1"
+  local module_manufacturer="$2"
+  local part_num="$3"
+  local size="$4"
+  local speed="$5"
+  local dasharo_version="$6"
+
+  declare -a new_rows
+
+  case $num_modules in
+  1)
+    conf="&#10004/-/-"
+    ;;
+  2)
+    conf="-/&#10004/-"
+    ;;
+  4)
+    conf="-/-/&#10004"
+    ;;
+  *)
+    conf="unknown"
+    ;;
+  esac
+
+  local entry="| $module_manufacturer | $part_num | $size | $speed | $conf | $dasharo_version | Dasharo HCL report |"
+
+  for row in "${new_rows[@]}"; do
+    if [[ "$row" == "$entry" ]]; then
+      return
+    fi
+  done
+
+  new_rows+=("$entry")
+  printf '%s\n' "${new_rows[@]}"
 }
 
 # :command.command_functions
@@ -493,71 +558,93 @@ dts_hclmgr_memory_command() {
   dasharo_version=$(extract_dasharo_version "$dir_name/logs/dmidecode.log")
 
   if [ -z "$dasharo_version" ]; then
-    if [ "$quiet" != "1" ]; then
-      echo "ERROR: Vendor BIOS HCL" >&2
-    fi
+    log "ERROR: Vendor BIOS HCL" >&2
     exit 1
   fi
 
-  # File containing the decode-dimms
+  # Files with logs for processing
   decodedimms_file="$dir_name/logs/decode-dimms.log"
+  dmidecode_file="$dir_name/logs/dmidecode.log"
 
   if [ ! -f "$decodedimms_file" ]; then
-    if [ "$quiet" != "1" ]; then
-      echo "ERROR: Decode DIMMs does not exist: $decodedimms_file" >&2
+    log "Decode DIMMs does not exist: $decodedimms_file, checking for dmidecode..."
+    if [ -s "$dmidecode_file" ]; then
+      log "But dmidecode exists, proceeding."
+    else
+      log "ERROR: Neither $decodedimms_file nor $dmidecode_file suitable for processing."
+      exit 1
     fi
-    exit 1
   fi
 
-  file_contents=$(<"$decodedimms_file")
+  # Try to use decode-dimms first, since the file exists and isn't empty
+  if [ -s "$decodedimms_file" ]; then
+    log "INFO: Trying decodedimms-based strategy."
+    file_contents=$(<"$decodedimms_file")
 
-  num_modules=$(grep -oP "(?<=Number of SDRAM DIMMs detected and decoded: )\d+" "$decodedimms_file" || true)
-  if [ -z "$num_modules" ]; then
-    if [ "$quiet" != "1" ]; then
-      echo "ERROR: No memory modules found" >&2
+    num_modules=$(grep -oP "(?<=Number of SDRAM DIMMs detected and decoded: )\d+" "$decodedimms_file" || true)
+    if [ -z "$num_modules" ]; then
+      log "ERROR: No memory modules found"
+      exit 1
     fi
-    exit 1
-  fi
 
-  if [ "$debug" ]; then
-    echo "Memory modules: $num_modules"
-  fi
+    if [ "$debug" ]; then
+      echo "Memory modules: $num_modules"
+    fi
 
-  declare -a new_rows
+    declare -a new_rows
 
-  # Loop through each bank
-  for ((bank = 1; bank <= num_modules; bank++)); do
+    # Loop through each bank
+    for ((bank = 1; bank <= num_modules; bank++)); do
 
-    module_manufacturer=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Module Manufacturer")
-    part_num=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Part Number")
-    size=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Size")
-    speed=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Maximum module speed")
+      module_manufacturer=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Module Manufacturer")
+      part_num=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Part Number")
+      size=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Size")
+      speed=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Maximum module speed")
 
-    case $num_modules in
-    1)
-      conf="&#10004/-/-"
-      ;;
-    2)
-      conf="-/&#10004/-"
-      ;;
-    4)
-      conf="-/-/&#10004"
-      ;;
-    *)
-      conf="unknown"
-      ;;
-    esac
+      generated_entry=$(generate_memory_table_entry "$num_modules" \
+        "$module_manufacturer" "$part_num" "$size" "$speed" "$dasharo_version")
+      new_rows+=("$generated_entry")
 
-    entry="| $module_manufacturer | $part_num | $size | $speed | $conf | $dasharo_version | Dasharo HCL report |"
-
-    for row in "${new_rows[@]}"; do
-      if [[ "$row" == "$entry" ]]; then
-        continue
-      fi
     done
-    new_rows+=("$entry")
+  fi
+  if [ -s "$dmidecode_file" ]; then
+    log "INFO: Trying dmidecode-based strategy."
 
-  done
+    # Read the file, but remove all the occurrences of "Configured Memory Speed"
+    # dmidecode entry, otherwise it could cause false positives when searching
+    # for "Speed" entry:
+    file_contents=$(sed '/Configured Memory Speed/d' "$dmidecode_file")
+    memory_handles=($(grep -o "Handle 0x...., DMI type 17" "$dmidecode_file" | grep -o "0x...." || true))
+    num_modules=${#memory_handles[@]}
+
+    if [ -z "$num_modules" ]; then
+      log "ERROR: No memory modules found" >&2
+      exit 1
+    fi
+
+    if [ "$debug" ]; then
+      echo "DEBUG: Reading file ${dmidecode_file}..."
+      echo "DEBUG: Memory modules: $num_modules"
+      echo "DEBUG: Memory handles: ${memory_handles[*]}"
+    fi
+
+    declare -a new_rows
+
+    for handle in "${memory_handles[@]}"; do
+
+      module_manufacturer=$(extract_lookup_string_from_dmidecode $handle "$file_contents" "Manufacturer:")
+      part_num=$(extract_lookup_string_from_dmidecode $handle "$file_contents" "Part Number:")
+      size=$(extract_lookup_string_from_dmidecode $handle "$file_contents" "Size:")
+      # See the comment on "Configured Memory Speed" from earlier - normally that
+      # pattern would be matched, but here it has already been removed.
+      speed=$(extract_lookup_string_from_dmidecode $handle "$file_contents" "Speed:")
+
+      generated_entry=$(generate_memory_table_entry "$num_modules" \
+        "$module_manufacturer" "$part_num" "$size" "$speed" "$dasharo_version")
+      new_rows+=("$generated_entry")
+
+    done
+  fi
 
   if [ "$update" ]; then
 
@@ -1047,7 +1134,7 @@ dts_hclmgr_mainboard_parse_requirements() {
 
 # :command.initialize
 initialize() {
-  declare -g version="0.1.0"
+  declare -g version="0.1.1"
   set -e
 
 }
