correct memory information printing
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>

diff --git a/dts-hclmgr b/dts-hclmgr
--- a/dts-hclmgr
+++ b/dts-hclmgr
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.4 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.7 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -435,7 +435,6 @@ dts_hclmgr_memory_command() {
     module_manufacturer=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Module Manufacturer")
     part_num=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Part Number")
     size=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Size")
-    mem_type=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Fundamental Memory type")
     speed=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Maximum module speed")
 
     case $num_modules in
@@ -449,7 +448,7 @@ dts_hclmgr_memory_command() {
         conf="unknown"
     esac
 
-  	echo "| $module_manufacturer | $part_num | $size | $mem_type | $speed | $conf | $dasharo_version | Dasharo HCL report |"
+  	echo "| $module_manufacturer | $part_num | $size | $speed | $conf | $dasharo_version | Dasharo HCL report |"
   done
 
 }
@@ -457,10 +456,27 @@ dts_hclmgr_memory_command() {
 # :command.function
 dts_hclmgr_gpu_command() {
   # src/gpu_command.sh
-  echo "# this file is located in 'src/gpu_command.sh'"
-  echo "# code for 'dts-hclmgr gpu' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+  # Variable containing the path to the tar.gz file
+  hcl_report=${args[hcl_report]}
+  force=${args[--force]}
+  quiet=${args[--quiet]}
+
+  echo "ERROR: Not implemented. Waiting for https://github.com/Dasharo/dasharo-issues/issues/462."
+  exit 1
+  # Extract the directory name from the file path
+  dir_name=$(basename "$hcl_report" .tar.gz)
+
+  perform_extraction "$dir_name" "$force" "$hcl_report"
+
+  # Extract the Dasharo Version using the function
+  dasharo_version=$(extract_dasharo_version "$dir_name/logs/dmidecode.log")
+
+  if [ ! -n "$dasharo_version" ];then
+  	if [ "$quiet" != "1" ]; then
+  		echo "ERROR: Vendor BIOS HCL"
+  	fi
+  	exit 1
+  fi
 
 }
 
