add support for gpu info retrival
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>

diff --git a/dts-hclmgr b/dts-hclmgr
--- a/dts-hclmgr
+++ b/dts-hclmgr
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.7 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.2.2 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -17,15 +17,7 @@ version_command() {
 
 # :command.usage
 dts_hclmgr_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "dts-hclmgr - Dasharo Tools Suite Hardware Compatibility List Manager\n"
-    echo
-
-  else
-    printf "dts-hclmgr - Dasharo Tools Suite Hardware Compatibility List Manager\n"
-    echo
-
-  fi
+  printf "dts-hclmgr - Dasharo Tools Suite Hardware Compatibility List Manager\n\n"
 
   printf "%s\n" "Usage:"
   printf "  dts-hclmgr [OPTIONS] COMMAND\n"
@@ -41,8 +33,8 @@ dts_hclmgr_usage() {
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
-    printf "%s\n" "Options:"
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Global Options:"
 
     # :command.usage_flags
     # :flag.usage
@@ -68,16 +60,7 @@ dts_hclmgr_usage() {
 
 # :command.usage
 dts_hclmgr_cpu_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "dts-hclmgr cpu - Generate CPU compatibility list documentation for Dasharo Universe website.\n"
-    echo
-
-  else
-    printf "dts-hclmgr cpu - Generate CPU compatibility list documentation for Dasharo Universe website.\n"
-    echo
-
-  fi
-
+  printf "dts-hclmgr cpu - Generate CPU compatibility list documentation for Dasharo Universe website.\n\n"
   printf "Alias: c\n"
   echo
 
@@ -87,7 +70,7 @@ dts_hclmgr_cpu_usage() {
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
+  if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -113,16 +96,7 @@ dts_hclmgr_cpu_usage() {
 
 # :command.usage
 dts_hclmgr_memory_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "dts-hclmgr memory - Generate memory compatibility list documentation for Dasharo Universe website.\n"
-    echo
-
-  else
-    printf "dts-hclmgr memory - Generate memory compatibility list documentation for Dasharo Universe website.\n"
-    echo
-
-  fi
-
+  printf "dts-hclmgr memory - Generate memory compatibility list documentation for Dasharo Universe website.\n\n"
   printf "Alias: m\n"
   echo
 
@@ -132,7 +106,7 @@ dts_hclmgr_memory_usage() {
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
+  if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -158,16 +132,7 @@ dts_hclmgr_memory_usage() {
 
 # :command.usage
 dts_hclmgr_gpu_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "dts-hclmgr gpu - Generate GPU compatibility list documentation for Dasharo Universe website.\n"
-    echo
-
-  else
-    printf "dts-hclmgr gpu - Generate GPU compatibility list documentation for Dasharo Universe website.\n"
-    echo
-
-  fi
-
+  printf "dts-hclmgr gpu - Generate GPU compatibility list documentation for Dasharo Universe website.\n\n"
   printf "Alias: g\n"
   echo
 
@@ -177,7 +142,7 @@ dts_hclmgr_gpu_usage() {
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
+  if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -203,16 +168,7 @@ dts_hclmgr_gpu_usage() {
 
 # :command.usage
 dts_hclmgr_mainboard_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "dts-hclmgr mainboard - Generate mainboard compatibility list documentation for Dasharo Universe website.\n"
-    echo
-
-  else
-    printf "dts-hclmgr mainboard - Generate mainboard compatibility list documentation for Dasharo Universe website.\n"
-    echo
-
-  fi
-
+  printf "dts-hclmgr mainboard - Generate mainboard compatibility list documentation for Dasharo Universe website.\n\n"
   printf "Alias: mb\n"
   echo
 
@@ -222,7 +178,7 @@ dts_hclmgr_mainboard_usage() {
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
+  if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -247,12 +203,16 @@ dts_hclmgr_mainboard_usage() {
 }
 
 # :command.normalize_input
+# :command.normalize_input_function
 normalize_input() {
-  local arg flags
+  local arg passthru flags
+  passthru=false
 
   while [[ $# -gt 0 ]]; do
     arg="$1"
-    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+    if [[ $passthru == true ]]; then
+      input+=("$arg")
+    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
       input+=("${BASH_REMATCH[1]}")
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -263,6 +223,9 @@ normalize_input() {
       for ((i = 0; i < ${#flags}; i++)); do
         input+=("-${flags:i:1}")
       done
+    elif [[ "$arg" == "--" ]]; then
+      passthru=true
+      input+=("$arg")
     else
       input+=("$arg")
     fi
@@ -270,12 +233,15 @@ normalize_input() {
     shift
   done
 }
+
 # :command.inspect_args
 inspect_args() {
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
-    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
   else
     echo args: none
   fi
@@ -293,9 +259,19 @@ inspect_args() {
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
     echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
   fi
 
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
+    done
+  fi
 }
 
 # :command.user_lib
@@ -461,8 +437,8 @@ dts_hclmgr_gpu_command() {
   force=${args[--force]}
   quiet=${args[--quiet]}
 
-  echo "ERROR: Not implemented. Waiting for https://github.com/Dasharo/dasharo-issues/issues/462."
-  exit 1
+  # echo "ERROR: Not implemented. Waiting for https://github.com/Dasharo/dasharo-issues/issues/462."
+  # exit 1
   # Extract the directory name from the file path
   dir_name=$(basename "$hcl_report" .tar.gz)
 
@@ -477,6 +453,66 @@ dts_hclmgr_gpu_command() {
   	fi
   	exit 1
   fi
+
+  # File containing the lspci
+  lspci_file="$dir_name/logs/lspci.log"
+
+  if [ ! -f "$lspci_file" ]; then
+  	if [ "$quiet" != "1" ]; then
+  		echo "ERROR: lspci does not extist: $lspci_file"
+  	fi
+  	exit 1
+  fi
+
+  # Count how many VGA controllers are detected
+  gpu_count=$(grep "VGA compatible controller \[0300\]" "$lspci_file"| wc -l)
+  vga_entries=$(grep "VGA compatible controller \[0300\]" "$lspci_file")
+
+  # Report if more than one VGA controller is found
+  if [ "$gpu_count" -gt 1 ]; then
+    mgt="Yes ($gpu_count)"
+  else
+      mgt="No"
+  fi
+
+  # Process each VGA entry separately
+  echo "$vga_entries" | while IFS= read -r entry; do
+    # Extract the GPU Vendor
+    gpu_vendor=$(echo "$entry" | awk -F ': ' '{print $2}'|cut -d'[' -f1|tr -d '\n')
+
+    # Check if the gpu_vendor starts with "NVIDIA"
+    if [[ "$gpu_vendor" == NVIDIA* ]]; then
+        # Extract the code name (third word in the string)
+        gpu_code_name=$(echo "$gpu_vendor" | awk '{print $3}')
+        # Extract GPU model (text inside the second square brackets)
+        gpu_model=$(echo "$entry" | awk -F'[][]' '{print $4}')
+        gpu_vendor="NVIDIA Corporation"
+    elif [[ "$gpu_vendor" == "Intel Corporation AlderLake-S GT1 " ]];then
+    	if [ "$quiet" != "1" ]; then
+    		echo "ERROR: This is iGPU: ->$entry<-, we don't have to report it"
+    	fi
+      # This is iGPU, we don't have to report it
+      exit 1
+    elif [[ "$gpu_vendor" == "Intel Corporation Device " ]];then
+    	if [ "$quiet" != "1" ]; then
+    		echo "ERROR: This is iGPU: ->$entry<-, we don't have to report it"
+    	fi
+      # This is integrated GPU, we don't have to report it
+      exit 1
+    elif [[ "$gpu_vendor" == "Advanced Micro Devices, Inc. " ]];then
+      gpu_code_name=$(echo "$entry" | awk -F '[:[]' '{print $5}' | sed 's/^\s*//g')
+      # Extract Model e.g.(Radeon RX 5600 OEM/5600 XT / 5700/5700 XT)
+      gpu_model=$(echo "$entry" | awk -F '[:[]' '{print $6}' | sed 's/^\s*//g')
+      gpu_vendor="Advanced Micro Devices, Inc."
+    else
+      echo $entry
+    fi
+
+    pcid=$(echo "$entry"|grep -oP '\[\K[0-9a-f]{4}:[0-9a-f]{4}')
+
+    echo "| $gpu_vendor | $gpu_code_name | $gpu_model | $pcid | $mgt | Dasharo HCL report |"
+
+  done
 
 }
 
@@ -633,8 +669,8 @@ dts_hclmgr_cpu_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['hcl_report']+x} ]]; then
-
           args['hcl_report']=$1
           shift
         else
@@ -650,6 +686,7 @@ dts_hclmgr_cpu_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['hcl_report']+x} ]]; then
     printf "missing required argument: HCL_REPORT\nusage: dts-hclmgr cpu HCL_REPORT\n" >&2
+
     exit 1
   fi
 
@@ -689,8 +726,8 @@ dts_hclmgr_memory_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['hcl_report']+x} ]]; then
-
           args['hcl_report']=$1
           shift
         else
@@ -706,6 +743,7 @@ dts_hclmgr_memory_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['hcl_report']+x} ]]; then
     printf "missing required argument: HCL_REPORT\nusage: dts-hclmgr memory HCL_REPORT\n" >&2
+
     exit 1
   fi
 
@@ -745,8 +783,8 @@ dts_hclmgr_gpu_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['hcl_report']+x} ]]; then
-
           args['hcl_report']=$1
           shift
         else
@@ -762,6 +800,7 @@ dts_hclmgr_gpu_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['hcl_report']+x} ]]; then
     printf "missing required argument: HCL_REPORT\nusage: dts-hclmgr gpu HCL_REPORT\n" >&2
+
     exit 1
   fi
 
@@ -801,8 +840,8 @@ dts_hclmgr_mainboard_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['hcl_report']+x} ]]; then
-
           args['hcl_report']=$1
           shift
         else
@@ -818,6 +857,7 @@ dts_hclmgr_mainboard_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['hcl_report']+x} ]]; then
     printf "missing required argument: HCL_REPORT\nusage: dts-hclmgr mainboard HCL_REPORT\n" >&2
+
     exit 1
   fi
 
@@ -836,6 +876,7 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
+  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
