src/: fix grep for memory modules
Signed-off-by: Eduard Kaverinskyi <eduard.kaverinskyi@3mdeb.com>

diff --git a/dts-hclmgr b/dts-hclmgr
--- a/dts-hclmgr
+++ b/dts-hclmgr
@@ -276,7 +276,7 @@ extract_dasharo_version() {
   local dasharo_version
 
   dasharo_line=$(grep 'Version: Dasharo' "$dmidecode_file")
-  dasharo_version=$(echo "$dasharo_line" | awk -F' ' '{print $4}')
+  dasharo_version=$(echo "$dasharo_line" | awk '{print $4}')
 
   echo "$dasharo_version"
 }
@@ -307,8 +307,10 @@ perform_extraction() {
 
     # Unpack the tar.gz file into the directory
     if ! tar -xzf "$hcl_report" -C "$dir_name"; then
-      echo "Error: Failed to extract archive: $hcl_report"
-      return 1
+      if [ "$quiet" != "1" ]; then
+        echo "Error: Failed to extract archive: $hcl_report"
+      fi
+      exit 1
     fi
 }
 
@@ -387,7 +389,7 @@ dts_hclmgr_memory_command() {
   # Extract the Dasharo Version using the function
   dasharo_version=$(extract_dasharo_version "$dir_name/logs/dmidecode.log")
 
-  if [ ! -n "$dasharo_version" ]; then
+  if [ -z "$dasharo_version" ];then
     if [ "$quiet" != "1" ]; then
       echo "ERROR: Vendor BIOS HCL"
     fi
@@ -404,9 +406,20 @@ dts_hclmgr_memory_command() {
     exit 1
   fi
 
-  file_contents=$(<$decodedimms_file)
+  file_contents=$(< "$decodedimms_file")
 
-  num_modules=$(grep -oP "(?<=Number of SDRAM DIMMs detected and decoded: )\d+" "$decodedimms_file")
+  num_modules=$(grep -oP "(?<=Number of SDRAM DIMMs detected and decoded: )\d+" "$decodedimms_file" || true)
+  if [ -z "$num_modules" ]; then
+    if [ "$quiet" != "1" ]; then
+      echo "ERROR: No memory modules found"
+    fi
+    exit 1
+  fi
+
+  if [ "$quiet" != "1" ]; then
+    echo "Memory modules: $num_modules"
+  fi
+
   # Loop through each bank
   for ((bank = 1; bank <= num_modules; bank++)); do
 
