src/: format according to pre-commit
Signed-off-by: Eduard Kaverinskyi <eduard.kaverinskyi@3mdeb.com>

diff --git a/dts-hclmgr b/dts-hclmgr
--- a/dts-hclmgr
+++ b/dts-hclmgr
@@ -269,6 +269,7 @@ inspect_args() {
 # src/lib/dasharo.sh
 #!/bin/bash
 # lib/dasharo.sh
+# shellcheck disable=SC2154
 
 extract_dasharo_version() {
   local dmidecode_file="$1"
@@ -282,55 +283,56 @@ extract_dasharo_version() {
 }
 
 perform_extraction() {
-    local dir_name=$1
-    local force=$2
-    local hcl_report=$3
+  local dir_name=$1
+  local force=$2
+  local hcl_report=$3
 
-    # Check if the directory already exists
-    if [ -d "$dir_name" ]; then
-        # Remove the directory if force flag is set or ask for confirmation
-        if [ "$force" = "1" ]; then
-            rm -rf "$dir_name"
-        else
-            echo "Warning: Directory $dir_name already exists."
-            read -p "Do you want to remove the directory and unpack the file again? (y/n) " confirm
-            if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
-                echo "Operation aborted."
-                return 0
-            fi
-            rm -rf "$dir_name"
-        fi
-    fi
-
-    # Create the directory
-    mkdir -p "$dir_name"
-
-    # Unpack the tar.gz file into the directory
-    if ! tar -xzf "$hcl_report" -C "$dir_name" >/dev/null 2>&1; then
-      if [ "$quiet" != "1" ]; then
-        echo "Error: Failed to extract archive: $hcl_report"
+  # Check if the directory already exists
+  if [ -d "$dir_name" ]; then
+    # Remove the directory if force flag is set or ask for confirmation
+    if [ "$force" = "1" ]; then
+      rm -rf "$dir_name"
+    else
+      echo "Warning: Directory $dir_name already exists."
+      read -p "Do you want to remove the directory and unpack the file again? (y/n) " confirm
+      if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
+        echo "Operation aborted."
+        return 0
       fi
-      exit 1
+      rm -rf "$dir_name"
     fi
+  fi
+
+  # Create the directory
+  mkdir -p "$dir_name"
+
+  # Unpack the tar.gz file into the directory
+  if ! tar -xzf "$hcl_report" -C "$dir_name" >/dev/null 2>&1; then
+    if [ "$quiet" != "1" ]; then
+      echo "Error: Failed to extract archive: $hcl_report"
+    fi
+    exit 1
+  fi
 }
 
 extract_lookup_string_from_decode_dimms() {
-	local bank_number="$1"
-	local file_contents="$2"
-	local lookup_string="$3"
+  local bank_number="$1"
+  local file_contents="$2"
+  local lookup_string="$3"
 
-	# Find the line number of the given bank line
-	bank_line_number=$(echo "$file_contents" | awk -v bank="$bank_number" '/bank/ && $3 == bank {print NR}')
+  # Find the line number of the given bank line
+  bank_line_number=$(echo "$file_contents" | awk -v bank="$bank_number" '/bank/ && $3 == bank {print NR}')
 
-	# Find the first occurrence of lookup string after the given bank line
-	match_line=$(echo "$file_contents" | awk -v line="$bank_line_number" 'NR > line && /'"$lookup_string"'/ {print NR; exit}')
+  # Find the first occurrence of lookup string after the given bank line
+  match_line=$(echo "$file_contents" | awk -v line="$bank_line_number" 'NR > line && /'"$lookup_string"'/ {print NR; exit}')
 
-	lookup_string_extracted=$(echo "$file_contents" | awk "NR == $match_line")
+  lookup_string_extracted=$(echo "$file_contents" | awk "NR == $match_line")
 
-	restul_tmp=$(echo "$lookup_string_extracted" | awk -F "$lookup_string" '{print $2}')
+  restul_tmp=$(echo "$lookup_string_extracted" | awk -F "$lookup_string" '{print $2}')
 
-	# Trim leading and trailing whitespace
-	echo $(echo "$restul_tmp" | awk '{$1=$1;print}')
+  # Trim leading and trailing whitespace
+  cleaned=$(echo "$restul_tmp" | awk '{$1=$1;print}')
+  echo "$cleaned"
 }
 
 # :command.command_functions
@@ -363,8 +365,8 @@ dts_hclmgr_cpu_command() {
   # Report
   source="Dasharo HCL Report"
 
-  if [ -n "$dasharo_version" ];then
-  	echo "| $cpu_model | $dasharo_version | $source |"
+  if [ -n "$dasharo_version" ]; then
+    echo "| $cpu_model | $dasharo_version | $source |"
   fi
 
 }
@@ -388,7 +390,7 @@ dts_hclmgr_memory_command() {
   # Extract the Dasharo Version using the function
   dasharo_version=$(extract_dasharo_version "$dir_name/logs/dmidecode.log")
 
-  if [ -z "$dasharo_version" ];then
+  if [ -z "$dasharo_version" ]; then
     if [ "$quiet" != "1" ]; then
       echo "ERROR: Vendor BIOS HCL"
     fi
@@ -405,7 +407,7 @@ dts_hclmgr_memory_command() {
     exit 1
   fi
 
-  file_contents=$(< "$decodedimms_file")
+  file_contents=$(<"$decodedimms_file")
 
   num_modules=$(grep -oP "(?<=Number of SDRAM DIMMs detected and decoded: )\d+" "$decodedimms_file" || true)
   if [ -z "$num_modules" ]; then
@@ -420,7 +422,7 @@ dts_hclmgr_memory_command() {
   fi
 
   # Loop through each bank
-  for ((bank=1; bank<=num_modules; bank++)); do
+  for ((bank = 1; bank <= num_modules; bank++)); do
 
     module_manufacturer=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Module Manufacturer")
     part_num=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Part Number")
@@ -428,14 +430,18 @@ dts_hclmgr_memory_command() {
     speed=$(extract_lookup_string_from_decode_dimms $bank "$file_contents" "Maximum module speed")
 
     case $num_modules in
-      1)
-        conf="&#10004/-/-";;
-      2)
-        conf="-/&#10004/-";;
-      4)
-        conf="-/-/&#10004";;
-      *)
-        conf="unknown"
+    1)
+      conf="&#10004/-/-"
+      ;;
+    2)
+      conf="-/&#10004/-"
+      ;;
+    4)
+      conf="-/-/&#10004"
+      ;;
+    *)
+      conf="unknown"
+      ;;
     esac
 
     echo "| $module_manufacturer | $part_num | $size | $speed | $conf | $dasharo_version | Dasharo HCL report |"
@@ -464,59 +470,59 @@ dts_hclmgr_gpu_command() {
   # Extract the Dasharo Version using the function
   dasharo_version=$(extract_dasharo_version "$dir_name/logs/dmidecode.log")
 
-  if [ ! -n "$dasharo_version" ];then
-  	if [ "$quiet" != "1" ]; then
-  		echo "ERROR: Vendor BIOS HCL"
-  	fi
-  	exit 1
+  if [ ! -n "$dasharo_version" ]; then
+    if [ "$quiet" != "1" ]; then
+      echo "ERROR: Vendor BIOS HCL"
+    fi
+    exit 1
   fi
 
   # File containing the lspci
   lspci_file="$dir_name/logs/lspci.log"
 
   if [ ! -f "$lspci_file" ]; then
-  	if [ "$quiet" != "1" ]; then
-  		echo "ERROR: lspci does not extist: $lspci_file"
-  	fi
-  	exit 1
+    if [ "$quiet" != "1" ]; then
+      echo "ERROR: lspci does not exist: $lspci_file"
+    fi
+    exit 1
   fi
 
   # Count how many VGA controllers are detected
-  gpu_count=$(grep "VGA compatible controller \[0300\]" "$lspci_file"| wc -l)
+  gpu_count=$(grep "VGA compatible controller \[0300\]" "$lspci_file" | wc -l)
   vga_entries=$(grep "VGA compatible controller \[0300\]" "$lspci_file")
 
   # Report if more than one VGA controller is found
   if [ "$gpu_count" -gt 1 ]; then
     mgt="Yes ($gpu_count)"
   else
-      mgt="No"
+    mgt="No"
   fi
 
   # Process each VGA entry separately
   echo "$vga_entries" | while IFS= read -r entry; do
     # Extract the GPU Vendor
-    gpu_vendor=$(echo "$entry" | awk -F ': ' '{print $2}'|cut -d'[' -f1|tr -d '\n')
+    gpu_vendor=$(echo "$entry" | awk -F ': ' '{print $2}' | cut -d'[' -f1 | tr -d '\n')
 
     # Check if the gpu_vendor starts with "NVIDIA"
     if [[ "$gpu_vendor" == NVIDIA* ]]; then
-        # Extract the code name (third word in the string)
-        gpu_code_name=$(echo "$gpu_vendor" | awk '{print $3}')
-        # Extract GPU model (text inside the second square brackets)
-        gpu_model=$(echo "$entry" | awk -F'[][]' '{print $4}')
-        gpu_vendor="NVIDIA Corporation"
-    elif [[ "$gpu_vendor" == "Intel Corporation AlderLake-S GT1 " ]];then
-    	if [ "$quiet" != "1" ]; then
-    		echo "ERROR: This is iGPU: ->$entry<-, we don't have to report it"
-    	fi
+      # Extract the code name (third word in the string)
+      gpu_code_name=$(echo "$gpu_vendor" | awk '{print $3}')
+      # Extract GPU model (text inside the second square brackets)
+      gpu_model=$(echo "$entry" | awk -F'[][]' '{print $4}')
+      gpu_vendor="NVIDIA Corporation"
+    elif [[ "$gpu_vendor" == "Intel Corporation AlderLake-S GT1 " ]]; then
+      if [ "$quiet" != "1" ]; then
+        echo "ERROR: This is iGPU: ->$entry<-, we don't have to report it"
+      fi
       # This is iGPU, we don't have to report it
       exit 1
-    elif [[ "$gpu_vendor" == "Intel Corporation Device " ]];then
-    	if [ "$quiet" != "1" ]; then
-    		echo "ERROR: This is iGPU: ->$entry<-, we don't have to report it"
-    	fi
+    elif [[ "$gpu_vendor" == "Intel Corporation Device " ]]; then
+      if [ "$quiet" != "1" ]; then
+        echo "ERROR: This is iGPU: ->$entry<-, we don't have to report it"
+      fi
       # This is integrated GPU, we don't have to report it
       exit 1
-    elif [[ "$gpu_vendor" == "Advanced Micro Devices, Inc. " ]];then
+    elif [[ "$gpu_vendor" == "Advanced Micro Devices, Inc. " ]]; then
       gpu_code_name=$(echo "$entry" | awk -F '[:[]' '{print $5}' | sed 's/^\s*//g')
       # Extract Model e.g.(Radeon RX 5600 OEM/5600 XT / 5700/5700 XT)
       gpu_model=$(echo "$entry" | awk -F '[:[]' '{print $6}' | sed 's/^\s*//g')
@@ -525,7 +531,7 @@ dts_hclmgr_gpu_command() {
       echo $entry
     fi
 
-    pcid=$(echo "$entry"|grep -oP '\[\K[0-9a-f]{4}:[0-9a-f]{4}')
+    pcid=$(echo "$entry" | grep -oP '\[\K[0-9a-f]{4}:[0-9a-f]{4}')
 
     echo "| $gpu_vendor | $gpu_code_name | $gpu_model | $pcid | $mgt | Dasharo HCL report |"
 
@@ -551,10 +557,10 @@ parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      --version | -v)
-        version_command
-        exit
-        ;;
+    --version | -v)
+      version_command
+      exit
+      ;;
 
     --help | -h)
       long_usage=yes
@@ -661,11 +667,11 @@ dts_hclmgr_cpu_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      --help | -h)
-        long_usage=yes
-        dts_hclmgr_cpu_usage
-        exit
-        ;;
+    --help | -h)
+      long_usage=yes
+      dts_hclmgr_cpu_usage
+      exit
+      ;;
 
     *)
       break
@@ -719,11 +725,11 @@ dts_hclmgr_memory_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      --help | -h)
-        long_usage=yes
-        dts_hclmgr_memory_usage
-        exit
-        ;;
+    --help | -h)
+      long_usage=yes
+      dts_hclmgr_memory_usage
+      exit
+      ;;
 
     *)
       break
@@ -777,11 +783,11 @@ dts_hclmgr_gpu_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      --help | -h)
-        long_usage=yes
-        dts_hclmgr_gpu_usage
-        exit
-        ;;
+    --help | -h)
+      long_usage=yes
+      dts_hclmgr_gpu_usage
+      exit
+      ;;
 
     *)
       break
@@ -835,11 +841,11 @@ dts_hclmgr_mainboard_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      --help | -h)
-        long_usage=yes
-        dts_hclmgr_mainboard_usage
-        exit
-        ;;
+    --help | -h)
+      long_usage=yes
+      dts_hclmgr_mainboard_usage
+      exit
+      ;;
 
     *)
       break
